name: dicee
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shake: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: asset/Roboto.ttf
    - family: Pacifico
      fonts:
        - asset: asset/Pacifico-Regular.ttf    